### ISSUE TITLE
Version 1.3: name 'RIG_PT_BinarySunWT' is not defined

### ISSUE THREAD

**Issue by fiftysquid** [PhysicalAddons/physical-starlight-and-atmosphere#28]
Error on init in Blender 2.9, 2.91, 2.92
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.90/scripts/modules/addon_utils.py", line 330, in enable
    importlib.reload(mod)
  File "/Applications/Blender.app/Contents/Resources/2.90/python/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/fiftysquid/Library/Application Support/Blender/2.90/scripts/addons/physical-starlight-atmosphere/__init__.py", line 83, in <module>
    RIG_PT_BinarySunWT,
NameError: name 'RIG_PT_BinarySunWT' is not defined
```

**Comment by karlisup** [comment]
Hi @fiftysquid, 
Try following this guide updating guide: https://www.physicaladdons.com/psa/updating/
Most of the time it's some old files intervening with new ones resulting in such errors.

The thing that always works for me when updating:
- removing addon in the Preferences Panel
- installing addon using Preferences Panel
- disabling/enabling addon

In the future, we have a plan to create an update script that would inform users of the addon new version and allow update it with single click, but till then it has to be done manually.

**Comment by fiftysquid** [comment]
That worked, thanks.
