### ISSUE TITLE
PSA 1.5.1 won't enable

### ISSUE THREAD

**Issue by ParodyVerse** [PhysicalAddons/physical-starlight-and-atmosphere#73]
**Describe the bug**
When I try to enable the addon it gives this error:
![image](https://user-images.githubusercontent.com/32398836/166119341-2969942d-de77-4e16-b448-7af01162914c.png)

**General information**
- Blender version: E-cycles 3.1.2
- Addon version: 1.5.1
- Engine: Not Applicable
- Operating System: Windows 10
- Other info that could be useful: [e.g. CPU, GPU, etc.]: 

**To Reproduce**
Download the addon and install. press the checkbox to enable and it won't enable.

**Screenshots**

**Comment by TysonParks** [comment]
I have the same issue. In fact I can't get any version of PSA to enable after 1.4.3 Beta. I have this issue on both my Apple Silicon 2021 MacBook Pro and my 2018 MacBook Pro.

**Describe the bug**
When I try to enable the addon it gives this error:
**Version 1.4.4:**

Traceback (most recent call last):
  File "/Applications/Blender 3.1.2.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/tysonparks/Library/Application Support/Blender/3.1/scripts/addons/physical-starlight-atmosphere/__init__.py", line 22, in <module>
    from . preferences import RIG_OT_OpenDocumentation, RIG_MT_addon_preferences, update_toolbar_label
ImportError: cannot import name 'RIG_OT_OpenDocumentation' from 'physical-starlight-atmosphere.preferences' (/Users/~/Library/Application Support/Blender/3.1/scripts/addons/physical-starlight-atmosphere/preferences.py)

**Version 1.5.0:**

Traceback (most recent call last):
  File "/Applications/Blender 3.1.2.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/tysonparks/Library/Application Support/Blender/3.1/scripts/addons/physical-starlight-atmosphere/__init__.py", line 39, in <module>
    from . preferences import RIG_OT_OpenDocumentation, RIG_MT_addon_preferences, update_toolbar_label
ImportError: cannot import name 'RIG_OT_OpenDocumentation' from 'physical-starlight-atmosphere.preferences' (/Users/~/Library/Application Support/Blender/3.1/scripts/addons/physical-starlight-atmosphere/preferences.py)

**Version 1.5.1:**

Traceback (most recent call last):
  File "/Applications/Blender 3.1.2.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/tysonparks/Library/Application Support/Blender/3.1/scripts/addons/physical-starlight-atmosphere/__init__.py", line 39, in <module>
    from . preferences import RIG_OT_OpenDocumentation, RIG_MT_addon_preferences, update_toolbar_label
ImportError: cannot import name 'RIG_OT_OpenDocumentation' from 'physical-starlight-atmosphere.preferences' (/Users/~/Library/Application Support/Blender/3.1/scripts/addons/physical-starlight-atmosphere/preferences.py)


**General information**

- Blender version: 3.1.2 Arm64 (Apple Silicon)
- Addon version: 1.5.1, 1.5.0, 1.4.4
- Engine: Not Applicable
- Operating System: Mac OS Monterey 12.2
- Other info that could be useful: [e.g. CPU, GPU, etc.]: Apple Silicon M1 Max

**To Reproduce**
Remove previous PSA addons. Download the addon and install. Press the checkbox to enable and it won't enable.

**Comment by karlisup** [comment]
I appreciate your patience! Usually, when updating from an older version although the addon is removed/deleted it gets cached and could cause an error related to the class registration. A restart of the Blender should fix the issue. Does the issue still persist today and did the restart help?

We will investigate how we can improve the addon so this doesn't repeat in the future as this has been a quite popular issue throughout all these years.

**Comment by TysonParks** [comment]
> I appreciate your patience! Usually, when updating from an older version although the addon is removed/deleted it gets cached and could cause an error related to the class registration. A restart of the Blender should fix the issue. Does the issue still persist today and did the restart help?
> 
> We will investigate how we can improve the addon so this doesn't repeat in the future as this has been a quite popular issue throughout all these years.

Hi @karlisup thanks for your reply. Yes this did work for me after a couple restarts with PSA 1.5.1 in Blender 3.1.2! Thank you.

Restart did not work for me in Blender 3.2 Beta, but that may be expected until after it moves to final release.

**Comment by ReinaVV** [comment]
No recent activity and no signs of the issue in newer builds.
Closing to keep the tracker tidy.
