### ISSUE TITLE
No atmosphere shader in Blender 3.4

### ISSUE THREAD

**Issue by vmxeo** [PhysicalAddons/physical-starlight-and-atmosphere#82]
**Describe the bug**
[Replace this with a clear and concise description of what the issue is about.]

**General information**
- Blender version: Blender 3.4
- Addon version: 1.6.2
- Engine: Eevee and Cycles
- Operating System: Windows 10
- Other info that could be useful: 

**To Reproduce**
When enabling starlight atmosphere, I get a starlight sun but no atmosphere world shader. The following error is logged in the Blender console:
```
Traceback (most recent call last):
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\physical-starlight-atmosphere\handlers.py", line 66, in enable_atmosphere
    link_nodes(loaded_nodes)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\physical-starlight-atmosphere\handlers.py", line 318, in link_nodes
    dictionary = get_links_for_node(node.name)
AttributeError: 'NoneType' object has no attribute 'name'
File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\physical-starlight-atmosphere\handlers.py", line 52, in enable_atmosphere

This is in a new scene in Blender 3.4.

```
**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by vmxeo** [comment]
One other important note - I was using the K-Cycles 3.4 build of Blender. This issue doesn't arise with vanilla Blender 3.4.1, which seems to indicate something weird with K-Cycles. I'll dig into that more.

**Comment by karlisup** [comment]
Hi @vmxeo,
Thank you for taking your time and reporting the issue. See more details here #83. Please, tell me if this fixes your issue. Meanwhile, I'll close this as a duplicate (though, it was reported before #83).
